// Optional real-browser acceptance runner: PLAYWRIGHT_MODULE points to an installed playwright module.
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
const {chromium,webkit}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const output=resolve(process.env.EVIDENCE_DIR||'evidence');mkdirSync(output,{recursive:true});
const stamp='2026-10-04T10:00:30+09:00';
const rows=[{id:'shared',tool:'Codex',source:'codex-cli',title:'匿名サンプル：スマホ表示の確認',project:'anonymous-fixture',start:stamp,last_activity:'2026-10-04T10:01:00+09:00',end:null,status:'notLoaded'}, {id:'shared',tool:'Claude',source:'claude-code',title:'匿名サンプル：日付と時刻の確認',project:'anonymous-fixture',start:stamp,end:'2026-10-04T12:00:00+09:00'}, {id:'cross',tool:'Codex',title:'匿名サンプル：前日から継続',start:'2026-10-03T23:59:30+09:00',end:'2026-10-04T00:00:30+09:00'},...Array.from({length:30},(_,i)=>({id:'anonymous-task-'+i,source:'dot-task',tool:'ChatGPT',title:i===0?'ChatGPT タスク s-task-0':'匿名タスク '+i,project:'anonymous-fixture',task_registered_at:stamp,snapshot_observed_at:stamp,latest_turn_status:i===1?'inProgress':'completed'}))];
rows.push({id:'observed-long',tool:'Codex',title:'匿名サンプル：終了不明の観測区間',project:'anonymous-fixture',start:'2026-10-04T09:00:00+09:00',last_activity:'2026-10-04T16:00:00+09:00'});
rows.push({id:'unknown',tool:'Codex',title:'Codex セッション unknown',project:'anonymous-fixture',start:'2026-10-04T14:00:00+09:00'});
const fixture={sessions:rows,warnings:[],source_scope:'匿名fixture · Codex / Claude / dot-task',synced_at:stamp};
writeFileSync(resolve(output,'anonymous-fixture.json'),JSON.stringify(fixture,null,2));
const server=createServer((req,res)=>{res.setHeader('Content-Type',req.url.startsWith('/api/')?'application/json':'text/html');res.end(req.url.startsWith('/api/')?JSON.stringify(fixture):readFileSync(process.env.HTML_FILE||'cloud/public/index.html'))});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;
const results=[];
try{for(const [name,engine] of [['chromium',chromium],['webkit',webkit]]){
 const browser=await engine.launch();
 for(const [width,height] of [[320,740],[375,812],[390,844],[430,932],[844,390],[1280,900]]){
 const context=await browser.newContext({viewport:{width,height},deviceScaleFactor:1,hasTouch:width<1000});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install({time:new Date('2026-10-04T10:00:00+09:00')});await page.goto(url);await page.waitForFunction(()=>document.querySelectorAll('.event').length>0);await page.clock.runFor(100);await page.locator(".calendar .event").first().waitFor({state:"visible"});
 const mobile=width<=650||(width<=1000&&height<=500);if(process.env.CAPTURE_BEFORE==='1'){await page.screenshot({path:resolve(output,`${name}-${width}-initial-viewport.png`)});await page.selectOption('#view','day-time');await page.locator('#now').click();if(!mobile)await page.selectOption('#view','day-time');await page.screenshot({path:resolve(output,`${name}-${width}-timeline.png`),fullPage:true});await context.close();continue}assert.equal(await page.locator('#view').inputValue(),'day');
 const overflow=await page.evaluate(()=>({body:document.documentElement.scrollWidth,viewport:innerWidth,days:document.querySelectorAll('.day').length}));assert.ok(overflow.body<=width,JSON.stringify(overflow));assert.equal(overflow.days,1);
 assert.equal(await page.locator('[data-session="Codex:unknown"] strong').innerText(),'作業名未受信');assert.match(await page.locator('[data-session="Codex:unknown"]').innerText(),/終了不明 · 開始記録のみ/);assert.match(await page.locator('[data-task-id="anonymous-task-1"]').innerText(),/取込時点：直近の実行が進行中/);if(mobile){const targets=await page.locator('.event').evaluateAll(es=>es.map(e=>({w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})));assert.ok(targets.every(e=>e.w>=44&&e.h>=44),JSON.stringify({width,name,targets}))}writeFileSync(resolve(output,`${name}-${width}-initial.html`),await page.content());await page.screenshot({path:resolve(output,`${name}-${width}-initial.png`),fullPage:true});await page.screenshot({path:resolve(output,`${name}-${width}-initial-viewport.png`),fullPage:false});
 const firstContent=await page.locator('.calendar .event,.calendar .empty').first().evaluate(e=>{const r=e.getBoundingClientRect();return {top:r.top,bottom:r.bottom,visibleHeight:Math.max(0,Math.min(r.bottom,innerHeight)-Math.max(r.top,0))}});if(width===844&&height===390){assert.ok(firstContent.visibleHeight>=44,JSON.stringify(firstContent));const controls=await page.locator('#prev,#today,#next,#tool,#view,#search,#refresh,#now,.viewer-notes summary').evaluateAll(es=>es.map(e=>({id:e.id,height:e.getBoundingClientRect().height})));assert.ok(controls.every(e=>e.height>=44),JSON.stringify(controls))}
 if(width<=650){assert.equal(await page.locator('#viewControls').evaluate(e=>e.open),false);const card=page.locator('.calendar .event').first(),firstFields=await card.locator('strong,small').evaluateAll(es=>es.map(e=>({text:e.textContent,top:e.getBoundingClientRect().top,bottom:e.getBoundingClientRect().bottom}))),secondHeading=await page.locator('.calendar .event strong').nth(1).boundingBox();assert.ok(firstFields.every(r=>r.top>=0&&r.bottom<=height),JSON.stringify(firstFields));assert.ok(secondHeading.y+secondHeading.height<=height,JSON.stringify(secondHeading));await page.locator('#viewControls summary').click();const controls=await page.locator('#tool,#search,#view,#refresh,#viewControls summary,#prev,#today,#next,#now').evaluateAll(es=>es.map(e=>({id:e.id,width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height})));assert.ok(controls.every(r=>r.width>=44&&r.height>=44),JSON.stringify(controls));writeFileSync(resolve(output,`${name}-${width}-priority.json`),JSON.stringify({firstFields,secondHeading,controls},null,2));await page.screenshot({path:resolve(output,`${name}-${width}-controls-viewport.png`),fullPage:false})}
 if(mobile){assert.equal(await page.locator('[data-session="Codex:cross"]').count(),1);await page.locator('#prev').click();assert.match(await page.locator('#range').innerText(),/2026\/10\/03/);await page.locator('#next').click();assert.match(await page.locator('#range').innerText(),/2026\/10\/04/)}
 await page.locator('#prev').click();await page.locator('#today').click();assert.match(await page.locator('#range').innerText(),/2026\/10\/04/);await page.selectOption('#view','day');await page.locator('[data-session="Codex:shared"]').click();
 if(width<=1000){assert.equal(await page.locator('#detailDialog').evaluate(e=>e.open),true);assert.match(await page.locator('#detailContent').innerText(),/終了日時\n不明/);await page.screenshot({path:resolve(output,`${name}-${width}-detail.png`),fullPage:true});await page.locator('#closeDetail').click();assert.equal(await page.locator('#detailDialog').evaluate(e=>e.open),false);assert.equal(await page.evaluate(()=>document.activeElement.dataset.session),'Codex:shared')}
 await page.selectOption('#view','day-time');const geometry=await page.locator('[data-session="Codex:shared"]').evaluate(e=>({top:parseFloat(e.style.top),height:parseFloat(e.style.height),bar:e.querySelector('.time-bar').className}));assert.ok(Math.abs(geometry.top-(64+(10+30/3600)*64))<.001);assert.ok(Math.abs(geometry.height-64/120)<.001);assert.match(geometry.bar,/observed/);
 assert.equal(await page.locator('[data-session="Codex:unknown"]').evaluate(e=>parseFloat(e.style.height)),0);assert.equal(await page.locator('[data-session="Codex:unknown"] .start-point').count(),1);assert.equal(await page.locator('[data-session="Codex:observed-long"]').evaluate(e=>parseFloat(e.style.height)),448);assert.match(await page.locator('[data-session="Codex:observed-long"]').getAttribute('title'),/終了不明/);await page.locator('#now').click();await page.selectOption('#view','day-time');await page.screenshot({path:resolve(output,`${name}-${width}-timeline.png`),fullPage:true});if(!mobile)await page.selectOption('#view','week');const group=page.locator('[data-task-group]');assert.equal(await group.count(),1);assert.equal(await group.getAttribute('data-task-group'),'30');if(mobile){const rect=await group.boundingBox();assert.ok(rect.width>=44&&rect.height>=44)}await group.click();assert.equal(await page.locator('#detailContent .event').count(),30);await page.locator('#detailContent .event').last().click();assert.match(await page.locator('#detailContent').innerText(),/登録日時から実行開始・終了・所要時間を推定していません/);if(width<=1000)await page.locator('#closeDetail').click();
 await page.locator('#now').click();assert.equal(await page.locator('#view').inputValue(),mobile?'day-time':'week');assert.ok(await page.locator('#calendar').evaluate(e=>e.scrollTop)>0);await page.screenshot({path:resolve(output,`${name}-${width}-now.png`),fullPage:true});
 await page.selectOption('#view','list');assert.equal(await page.locator('.task-card').count(),30);await page.selectOption('#view','day');await page.locator('#search').fill('nonexistent');assert.equal(await page.locator('.event').count(),0);await page.locator('#search').fill('');assert.equal(await page.locator('.task-card').count(),30);
 await page.route('**/api/sessions*',route=>route.fulfill({json:{sessions:[],warnings:[],source_scope:'匿名clear fixture',synced_at:stamp}}));await page.locator('#refresh').click();await page.waitForFunction(()=>document.querySelectorAll('.event').length===0);if(width===844&&height===390){const empty=await page.locator('.calendar .empty').first().boundingBox();assert.ok(empty.y+empty.height<=height);await page.screenshot({path:resolve(output,`${name}-${width}-empty-viewport.png`),fullPage:false})}await page.unroute('**/api/sessions*');await page.locator('#refresh').click();await page.waitForFunction(()=>document.querySelectorAll('.task-card').length===30);await page.route('**/api/sessions*',route=>route.fulfill({json:{...fixture,sessions:rows.map(s=>({...s,title:s.source==='dot-task'?'ChatGPT タスク '+s.id.slice(-8):s.tool+' セッション '+s.id.slice(0,8)}))}}));await page.locator('#refresh').click();await page.waitForFunction(()=>document.querySelector('#privacy').textContent.includes('匿名タイトル形式'));await page.unroute('**/api/sessions*');
 await page.setViewportSize({width:390,height:844});await page.clock.runFor(200);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);results.push({engine:name,width,height,overflow,firstContent,geometry,errors,pass:true});await context.close();
 }await browser.close();
}}finally{server.close()}
writeFileSync(resolve(output,'browser-results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
